<?php
	include "configuration/header.php";
?>
<table border="0" style="width:80%; text-align:left; vertical-align:top" cellpadding="4" cellspacing="0">
<tr><th colspan="2">
	<h1 style="margin:0px 0px 5px 0px">AdHound&trade; Support</h1>
</th></tr>
<tr><td style="width:200px; vertical-align:top; text-align:left; white-space:nowrap">
	<ul>
		<li><a href="#locations">Locations</a>
		<ul>
			<li><a href="#locations_regions">Regions</a></li>
			<li><a href="#locations_contract">Contract Term</a>
			<ul>
				<li><a href="#locations_contract_flat">Contract Flat Rate</a></li>
				<li><a href="#locations_contract_percentage">Contract Percentage</a></li>
			</ul>
			</li>
		</ul>
		</li>
	</Ul>
</td>
<td style="width:auto; vertical-align:top; text-align:left">
	<p>If you have any more questions, please contact our support team at <a href="mailto:support@itsadvertising.com?subject=AdHound%20Support">support@itsadvertising.com</a>.</p>
<ul style="list-style-type:none">
	<li><a id="locations"><h1>Locations</h1></a>
	<p>Locations are where advertisements are placed.</p>
	<ul style="list-style-type:none">
		<li><img src="images/howto/LocationContractTermsDropdown1.jpg" style="float:right" alt="Location Contract Term" />
		<a id="locations_contract"><h2>Contract Term</h2></a>
		<p>The Location Contract Term designates a specific percentage or flat rate amount owed to the location by It's Advertising, LLC on a weekly, bimonthly, 
		monthly, quarterly, biannually, or annually basis.</p>
		<p>If a desired contact term is not listed in the dropdown you can add a term by selecting "Other". If the contract term 
		is open end or not available select "None".</p>
		<img src="images/howto/LocationContractTermsOtherFlatRate.jpg" alt="Location Contract Term Flat Rate" />
		<img src="images/howto/LocationContractTermsOtherPercentage.jpg" alt="Location Contract Term Percentage" />
		<ul style="list-style-type:none; margin-top:10px">
			<li><img src="images/howto/LocationContractTermsQuarterlyFlat.jpg" style="float:right" alt="Location Contract Term Quarterly Flat Rate" />
			<a id="locations_contract_flat"><h3>Contract Flat Rate</h3></a>
			<p>The flat rate amount owed to the location by It's Advertising, LLC is on a weekly, bimonthly, 
			monthly, quarterly, biannually, or annually basis for the duration of the contract term. 
			The amount is only based on the set amount.</p>
			
			</li>
			<li><img src="images/howto/LocationContractTermsQuarterlyPercentage.jpg" style="float:right" alt="Location Contract Term Quarterly Percentage" />
			<a id="locations_contract_percentage"><h3>Contract Percentage</h3></a>
			<p>The percentage amount owed to the location by It's Advertising, LLC is on a weekly, bimonthly, 
			monthly, quarterly, biannually, or annually basis for the duration of the contract term. 
			The amount is calculated by taking a set percentage times the revenue generated by each advertisement 
			at the location. The percentage only applies to unexpired ads that are with in the payment intervals. For example, 
			if an advertisment expires before the forth quarter of a contract term, the percentage amount owed will only 
			apply to the first, second, and third quarters.</p>
			
			</li>
		</ul>
		</li>
		
	</ul>
	</li>
</ul>
</td></tr>
</table>
<?php
	include "configuration/footer.php";
?>