DROP DATABASE IF EXISTS `test`;
CREATE DATABASE `test` CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `test`;

CREATE TABLE test1 (
    a1 INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (a1)
) ENGINE=InnoDB AUTO_INCREMENT=1;
CREATE TABLE test2 (
    b2 INT NOT NULL AUTO_INCREMENT,
    b1 INT NOT NULL,
    b21 VARCHAR(24) GENERATED ALWAYS AS (CONCAT('b1','b2')),
    PRIMARY KEY (b2),
    CONSTRAINT `test1_fk` FOREIGN KEY (b1) REFERENCES test1(a1) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;
/*
CREATE TABLE test3 (
    a3 INT NOT NULL AUTO_INCREMENT,
    a12 INT NOT NULL,
    PRIMARY KEY (a3),
    CONSTRAINT `test2_fk` FOREIGN KEY (a12) REFERENCES test2(a1,a2) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1;
*/

delimiter |

CREATE TRIGGER testref AFTER INSERT ON test1
  FOR EACH ROW
  BEGIN
    INSERT INTO test2 SET a21 = NEW.a1;
    /* INSERT INTO test3 SET a12 = NEW.a1NEW.a2; */
  END;
|

delimiter ;

INSERT INTO test1 (a1) VALUES (1);